<?php
    $buttonTitle = $this->__('Add & Pay');
?>
<div class="addandpay-wrapper" style="text-align: right; margin-top: .5em; ">
    <input type="hidden" name="firecheckout" value="0" />
    <button type="button" title="<?php echo $buttonTitle ?>" id="product-addandpay-button" class="button btn-cart" onclick="$(this).siblings('[name=firecheckout]')[0].value='1'; productAddToCartForm.submit(this);"><span><span><?php echo $buttonTitle ?></span></span></button>
</div>
